# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created']},
        ),
    ]
