# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0003_auto_20160828_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='period',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
