# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0004_auto_20161007_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(),
        ),
    ]
